[project]
name = "gliner-as-a-service"
version = "0.1.0"
description = "GLiNER as a Service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.10",
    "celery[redis]>=5.4.0",
    "certifi>=2024.8.30",
    "datasets>=3.1.0",
    "fastapi[standard]>=0.115.6",
    "flask-cors>=5.0.0",
    "flower>=2.0.1",
    "flupy>=1.2.1",
    "gliner>=0.2.13",
    "gputil>=1.4.0",
    "hf-transfer>=0.1.8",
    "locust>=2.32.4",
    "loguru>=0.7.3",
    "requests>=2.32.3",
    "scikit-learn>=1.6.0",
    "setuptools>=75.6.0",
    "torch>=2.5.1",
    "tornado>=6.4.2",
    "urllib3>=2.2.3",
    "valkey[libvalkey]>=6.0.2",
]

[project.optional-dependencies]
ui = [
    "polars>=1.17.1",
    "st-annotated-text>=4.0.1",
    "streamlit>=1.40.2",
    "watchdog>=6.0.0",
]

[tool.setuptools.packages.find]
where = ["app/"]
include = ["src"]

[tool.uv]
dev-dependencies = ["black>=24.10.0", "isort>=5.13.2", "ruff>=0.8.2"]
